language: python

dist: trusty

python:
    - "3.4"
    - "3.5"

services:
    - mongodb
    - redis-server

addons:
    apt:
        sources:
            - elasticsearch-2.x
        packages:
            - elasticsearch

cache:
  - pip

before_install:
    - sudo apt-get purge elasticsearch
    - sudo apt-get install -t stable elasticsearch
    - sudo service elasticsearch restart

install:
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt

script:
    - flake8
    - python newsroom_tests.py
